### ISSUE TITLE
experiments directory cleanup and readme

### ISSUE THREAD

**Issue by jmcook1186** [jmcook1186/biosnicar-py#31]
added /experiments module to contain miscellaneous applications of the biosnicar model code (e.g. inverter, LUT builder, parallelized versions, field-model comparisons etc). 

Now the dir needs tidying up. Not sure what this looks like yet, but could be splitting the content of utils.py into multiple scripts, or perhaps it's just a better organised and documented driver script (or something else).

Either way, the mod also needs a README with good explanations of the contents and how it can be used.

tagging @lcvl41 to flag this change to the repo structure

**Comment by mohammadfarari1360** [comment]
Okay

**Comment by jmcook1186** [comment]
closing as out of date- the experiments folder is deprecated and removed
