### ISSUE TITLE
biosnicar doesnt launch anymore

### ISSUE THREAD

**Issue by tilmanmarschallek** [jmcook1186/biosnicar-py#90]
Hey biosnicar team,
I used your app with great interest because it helped a lot at work.
unfortunately since 4 or 5 days I get an error massage when starting it.
What is the problem?
Thank you.
Have a nice week.
Greetings,
Tilman

**Comment by jmcook1186** [comment]
Hi @tilmanmarschallek 

can you give some more details for "doesn't launch"?
how are you trying to run biosnicar?
what error message are you getting?

I did make some changes to the repo structure last week, but afaict there's nothing broken. Possible you need to update some paths. Respond with some more details and I'll try to debug you.

**Comment by tilmanmarschallek** [comment]
Hi @jmcook1186 
Of course I will clarify my problem.
I used biosnicar in the browser with this link.
When I open it now, it only shows "Oh no.Error running app. If this keeps happening, please contact support.
This is how i came to this thread.
Thanks a lot.
Greetings,
Tilman

**Comment by jmcook1186** [comment]
Ah ok, yes please try this update url: https://bit.ly/bio-snicar

**Comment by tilmanmarschallek** [comment]
It worked. Thanks.
Have a nice rest of the day.
Greetings,
Tilman

**Comment by jmcook1186** [comment]
Great - closing this out
