### ISSUE TITLE
'ModelConfig' object is not subscriptable

### ISSUE THREAD

**Issue by LeaHartl** [jmcook1186/biosnicar-py#91]
Hi, I am running into issues when I try to add water coating in the input.yaml file under ICE/WATER. I get a Type Error "'ModelConfig' object is not subscriptable" in column_OPs.py, line 156, in the add_water_coating function.
I did not change anything else and it works fine without the water coating as far as I can tell (it runs without error if the "WATER" value is less than or equal to the "RDS" value.
It seems like this might be an issue with the python version but I am not sure and have not been able to pinoint it. I am running python 3.9.13. Any advice on this?
Thank you!

**Comment by jmcook1186** [comment]
Hi - thanks for raising the issue - I am able to reproduce the error locally, and can see the problem - I'll have a fix pushed shortly.

**Comment by jmcook1186** [comment]
ok pushed a fix - let me know if this fixes things for you

**Comment by LeaHartl** [comment]
thanks for the super quick response! it seems that mie_coated_water_spheres.py now runs but I get a NameError for 'file_ice' a couple of lines further down: 
column_OPs.py line 168, in add_water_coating
    with xr.open_dataset(file_ice) as temp:
NameError: name 'file_ice' is not defined

**Comment by jmcook1186** [comment]
Doh - yes ok please pull and try again - it should be fixed.

**Comment by LeaHartl** [comment]
yes it's running nicely now! Thank you!!

**Comment by jmcook1186** [comment]
Great! Closing this out then
